### ISSUE TITLE
test fails on PostgreSQL 10

### ISSUE THREAD

**Issue by coderfox** [adwhit/diesel-derive-enum#20]
```shell
$ psql --version
psql (PostgreSQL) 10.4

$ PG_TEST_DATABASE_URL=postgres://postgres@127.0.0.1 cargo test --features postgres
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/tests-61de74e2f6241362

running 5 tests
test nullable::nullable_enum_round_trip ... FAILED
test rename::rename_round_trip ... ok
test nullable::not_nullable_enum_round_trip ... ok
test simple::enum_round_trip ... FAILED
test simple::filter_by_enum ... FAILED

failures:

---- nullable::nullable_enum_round_trip stdout ----
	thread 'nullable::nullable_enum_round_trip' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "column \"my_enum\" is of type my_enum but expression is of type pg_temp_7.my_enum")', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- simple::enum_round_trip stdout ----
	thread 'simple::enum_round_trip' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "column \"my_enum\" is of type my_enum but expression is of type pg_temp_7.my_enum")', libcore/result.rs:945:5

---- simple::filter_by_enum stdout ----
	thread 'simple::filter_by_enum' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "column \"my_enum\" is of type my_enum but expression is of type pg_temp_7.my_enum")', libcore/result.rs:945:5


failures:
    nullable::nullable_enum_round_trip
    simple::enum_round_trip
    simple::filter_by_enum

test result: FAILED. 2 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'

```

I think this failure is related to behavior changes in `TEMP` in PostgreSQL 10.

**Comment by adwhit** [comment]
This looks like the same as #17?

**Comment by coderfox** [comment]
Yes. Thanks for your help and sorry for my disturbing.
